[build]
builder = "nixpacks"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production.variables]
APP_ENV = "production"
APP_DEBUG = "false"

[[environments.production.plugins]]
type = "postgresql"
